using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;


namespace Content.Client._Floof.NebulaComputing.UI;


[GenerateTypedNameReferences]
public sealed partial class InfoTab : Control
{
    public InfoTab()
    {
        RobustXamlLoader.Load(this);
    }
}

