using Content.Shared.FloofStation.NebulaComputing.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;


namespace Content.Client.Floofstation.NebulaComputing.UI;


[GenerateTypedNameReferences]
public sealed partial class AssemblerTab : Control
{
   public event Action<string>? OnRunRequested;

   private bool _codeChangedSinceLastState = false;

    public AssemblerTab()
    {
        RobustXamlLoader.Load(this);

        RunButton.OnPressed += _ => RequestRun();
        ClearOutputButton.OnPressed += _ => ClearOutput();

        CodeEdit.OnTextChanged += _ => _codeChangedSinceLastState = true;
    }

    public void Populate(ProgrammableComputerBUIState msg)
    {
        RunButton.Disabled = msg.IsActivelyAssembling;

        if (msg.LastRunAssembly is { } assembly && !_codeChangedSinceLastState)
            CodeEdit.TextRope = new Rope.Leaf(assembly);
    }

    public void RequestRun()
    {
        var code = Rope.Collapse(CodeEdit.TextRope).Trim();
        if (code.Length == 0)
        {
            PrintOutput("Please enter some code before requesting a run.");
        }

        OnRunRequested?.Invoke(code);
        _codeChangedSinceLastState = false;
    }

    public void ClearOutput()
    {
        Output.Text = "";
    }

    public void PrintOutput(string output)
    {
        Output.Text += output + "\n";
    }
}

