using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;


namespace Content.Client.Floofstation.NebulaComputing.UI;


[GenerateTypedNameReferences]
public sealed partial class AssemblerTab : Control
{
    public AssemblerTab()
    {
        RobustXamlLoader.Load(this);
    }
}

