using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;


namespace Content.Client.Floofstation.NebulaComputing.UI;


[GenerateTypedNameReferences]
public sealed partial class ConsoleOutputTab : Control
{
    public ConsoleOutputTab()
    {
        RobustXamlLoader.Load(this);
    }
}

